services:
    danieltj.verifiedprofiles.listener:
        class: danieltj\verifiedprofiles\event\listener
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@notification_manager'
            - '@request'
            - '@template'
            - '@user'
            - '@danieltj.verifiedprofiles.includes.functions'
        tags:
            - { name: event.listener }

    danieltj.verifiedprofiles.includes.functions:
        class: danieltj\verifiedprofiles\includes\functions
        arguments:
            - '@config'
            - '@dbal.conn'

    danieltj.verifiedprofiles.notification.type.verified:
        class: danieltj\verifiedprofiles\notification\type\verified
        parent: notification.type.base
        shared: false
        tags: [ { name: notification.type } ]
        calls:
            - [ 'set_user_loader', [ '@user_loader' ] ]
            - [ 'set_functions', [ '@danieltj.verifiedprofiles.includes.functions' ] ]
